"""Release-notes page generation and drift protection."""

from __future__ import annotations

import pathlib

from scripts import gen_changelog_page


def test_build_page_replaces_heading_and_preserves_changelog(tmp_path: pathlib.Path) -> None:
    source = tmp_path / "CHANGELOG.md"
    source.write_text(
        "# Changelog\n\n## [Unreleased]\n\n"
        "- [Overview](docs/README.md), [guide](docs/commands.md), and "
        "[examples](examples/).\n",
        encoding="utf-8",
    )
    rendered = gen_changelog_page.build_page(source)
    assert rendered.startswith("<!-- Generated by scripts/gen_changelog_page.py")
    assert "# Release notes\n" in rendered
    assert "# Changelog" not in rendered
    assert "## [Unreleased]" in rendered
    assert "](commands.md)" in rendered
    assert "](./)" in rendered
    assert "](README.md)" not in rendered
    assert "](docs/commands.md)" not in rendered
    assert "https://github.com/ZelAnton/processkit-py/tree/main/examples/" in rendered


def test_check_detects_and_write_repairs_drift(tmp_path: pathlib.Path) -> None:
    source = tmp_path / "CHANGELOG.md"
    # A distinct basename matters on case-insensitive filesystems: CHANGELOG.md
    # and changelog.md otherwise name the same file on Windows.
    page = tmp_path / "generated.md"
    source.write_text("# Changelog\n\n## [1.0.0]\n", encoding="utf-8")
    page.write_text("stale\n", encoding="utf-8")
    assert not gen_changelog_page.check(source, page)
    gen_changelog_page.write(source, page)
    assert gen_changelog_page.check(source, page)


def test_committed_release_notes_page_is_current() -> None:
    assert gen_changelog_page.check()
