"""Type stubs for the compiled `_processkit` extension module.

mypy cannot see into the PyO3 cdylib, so the public surface is declared here.
Keep this in sync with `src/lib.rs`.
"""

from __future__ import annotations

import os
from collections.abc import AsyncIterator, Callable, Sequence
from types import TracebackType
from typing import Literal

StrPath = str | os.PathLike[str]

class ProcessResult:
    """The captured result of a finished run. A non-zero exit, a timeout, and a
    signal-kill are all reported as data here — never raised by `output()`."""

    @property
    def stdout(self) -> str: ...
    @property
    def stderr(self) -> str: ...
    @property
    def code(self) -> int | None: ...
    @property
    def is_success(self) -> bool: ...
    @property
    def timed_out(self) -> bool: ...
    @property
    def signal(self) -> int | None: ...
    @property
    def program(self) -> str: ...
    @property
    def duration_seconds(self) -> float: ...
    def combined(self) -> str: ...
    def __repr__(self) -> str: ...

class Command:
    """A command builder. Builder methods return a new `Command`."""

    def __init__(self, program: StrPath, args: Sequence[str] | None = ...) -> None: ...
    def arg(self, arg: str) -> Command: ...
    def args(self, args: Sequence[str]) -> Command: ...
    def cwd(self, path: StrPath) -> Command: ...
    def env(self, key: str, value: str) -> Command: ...
    def stdin_bytes(self, data: bytes) -> Command: ...
    def stdin_text(self, text: str) -> Command: ...
    def keep_stdin_open(self) -> Command: ...
    def timeout(self, seconds: float) -> Command: ...
    def output(self) -> ProcessResult: ...
    def run(self) -> str: ...
    def exit_code(self) -> int: ...
    def probe(self) -> bool: ...
    async def aoutput(self) -> ProcessResult: ...
    async def arun(self) -> str: ...
    async def aexit_code(self) -> int: ...
    async def aprobe(self) -> bool: ...
    async def astart(self) -> RunningProcess: ...
    def pipe(self, other: Command) -> Pipeline: ...
    def __or__(self, other: Command) -> Pipeline: ...
    def __repr__(self) -> str: ...

class Pipeline:
    """A shell-free pipeline `a | b | c`."""

    def pipe(self, other: Command) -> Pipeline: ...
    def __or__(self, other: Command) -> Pipeline: ...
    def timeout(self, seconds: float) -> Pipeline: ...
    def output(self) -> ProcessResult: ...
    def run(self) -> str: ...
    def exit_code(self) -> int: ...
    def probe(self) -> bool: ...
    async def aoutput(self) -> ProcessResult: ...
    async def arun(self) -> str: ...
    async def aexit_code(self) -> int: ...
    async def aprobe(self) -> bool: ...
    def __repr__(self) -> str: ...

class Outcome:
    """How a process ended."""

    @property
    def code(self) -> int | None: ...
    @property
    def signal(self) -> int | None: ...
    @property
    def timed_out(self) -> bool: ...
    @property
    def is_success(self) -> bool: ...
    def __repr__(self) -> str: ...

class Finished:
    """A process's outcome plus captured stderr (stdout was streamed)."""

    @property
    def outcome(self) -> Outcome: ...
    @property
    def stderr(self) -> str: ...
    @property
    def code(self) -> int | None: ...
    @property
    def is_success(self) -> bool: ...
    def __repr__(self) -> str: ...

class OutputEvent:
    """One captured line and the stream it came from."""

    @property
    def stream(self) -> str: ...
    @property
    def is_stderr(self) -> bool: ...
    @property
    def text(self) -> str: ...
    def __repr__(self) -> str: ...

class StdoutLines:
    """Async iterator over a process's stdout, line by line."""

    def __aiter__(self) -> AsyncIterator[str]: ...
    async def __anext__(self) -> str: ...

class OutputEvents:
    """Async iterator over stdout + stderr as interleaved `OutputEvent`s."""

    def __aiter__(self) -> AsyncIterator[OutputEvent]: ...
    async def __anext__(self) -> OutputEvent: ...

class ProcessStdin:
    """A writable handle to a running process's stdin (all methods awaitable)."""

    async def write(self, data: bytes) -> None: ...
    async def write_line(self, line: str) -> None: ...
    async def flush(self) -> None: ...
    async def close(self) -> None: ...

class RunningProcess:
    """A handle to a started process: stream output, write stdin, await exit."""

    @property
    def pid(self) -> int | None: ...
    def stdout_lines(self) -> StdoutLines: ...
    def output_events(self) -> OutputEvents: ...
    def take_stdin(self) -> ProcessStdin | None: ...
    def start_kill(self) -> None: ...
    async def wait(self) -> Outcome: ...
    async def finish(self) -> Finished: ...
    async def output(self) -> ProcessResult: ...
    async def shutdown(self, grace_seconds: float) -> Outcome: ...
    def __repr__(self) -> str: ...

class ProcessGroupStats:
    """A snapshot of a `ProcessGroup`'s resource usage."""

    @property
    def active_process_count(self) -> int: ...
    @property
    def peak_memory_bytes(self) -> int | None: ...
    @property
    def total_cpu_time_seconds(self) -> float | None: ...
    def __repr__(self) -> str: ...

class ProcessGroup:
    """A kill-on-drop container for a process tree; use as a (async) context manager."""

    def __init__(
        self,
        *,
        memory_max: int | None = ...,
        max_processes: int | None = ...,
        cpu_quota: float | None = ...,
        shutdown_timeout: float | None = ...,
        escalate_to_kill: bool | None = ...,
    ) -> None: ...
    def __enter__(self) -> ProcessGroup: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: TracebackType | None = ...,
    ) -> Literal[False]: ...
    async def __aenter__(self) -> ProcessGroup: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: TracebackType | None = ...,
    ) -> Literal[False]: ...
    def start(self, command: Command) -> RunningProcess: ...
    async def astart(self, command: Command) -> RunningProcess: ...
    @property
    def mechanism(self) -> str: ...
    def members(self) -> list[int]: ...
    def signal(self, name: str) -> None: ...
    def suspend(self) -> None: ...
    def resume(self) -> None: ...
    def terminate_all(self) -> None: ...
    def stats(self) -> ProcessGroupStats: ...
    def shutdown(self) -> None: ...
    async def ashutdown(self) -> None: ...
    def __repr__(self) -> str: ...

class SupervisionOutcome:
    """The result of a `Supervisor.run()`."""

    @property
    def final_result(self) -> ProcessResult: ...
    @property
    def restarts(self) -> int: ...
    @property
    def stopped(self) -> str: ...
    @property
    def storm_pauses(self) -> int: ...
    def __repr__(self) -> str: ...

class Supervisor:
    """Keep a command alive: restart per policy with backoff until a stop condition."""

    def __init__(
        self,
        command: Command,
        *,
        restart: str | None = ...,
        max_restarts: int | None = ...,
        backoff_initial: float | None = ...,
        backoff_factor: float | None = ...,
        max_backoff: float | None = ...,
        jitter: bool | None = ...,
        stop_when: Callable[[ProcessResult], bool] | None = ...,
    ) -> None: ...
    def run(self) -> SupervisionOutcome: ...
    async def arun(self) -> SupervisionOutcome: ...

class Reply:
    """A canned reply for a `ScriptedRunner` rule."""

    @staticmethod
    def ok(stdout: str) -> Reply: ...
    @staticmethod
    def fail(code: int, stderr: str) -> Reply: ...
    @staticmethod
    def timeout() -> Reply: ...
    @staticmethod
    def signalled(signal: int | None = ...) -> Reply: ...
    @staticmethod
    def pending() -> Reply: ...
    @staticmethod
    def lines(lines: Sequence[str]) -> Reply: ...
    def with_stdout(self, stdout: str) -> Reply: ...
    def __repr__(self) -> str: ...

class Runner:
    """The real process runner — inject it for testable code."""

    def __init__(self) -> None: ...
    def output(self, command: Command) -> ProcessResult: ...
    def run(self, command: Command) -> str: ...
    def exit_code(self, command: Command) -> int: ...
    def probe(self, command: Command) -> bool: ...
    def start(self, command: Command) -> RunningProcess: ...
    async def aoutput(self, command: Command) -> ProcessResult: ...
    async def arun(self, command: Command) -> str: ...
    async def aexit_code(self, command: Command) -> int: ...
    async def aprobe(self, command: Command) -> bool: ...
    async def astart(self, command: Command) -> RunningProcess: ...
    def __repr__(self) -> str: ...

class ScriptedRunner:
    """A scripted test double for `Runner`."""

    def __init__(self) -> None: ...
    def on(self, prefix: Sequence[str], reply: Reply) -> None: ...
    def fallback(self, reply: Reply) -> None: ...
    def output(self, command: Command) -> ProcessResult: ...
    def run(self, command: Command) -> str: ...
    def exit_code(self, command: Command) -> int: ...
    def probe(self, command: Command) -> bool: ...
    def start(self, command: Command) -> RunningProcess: ...
    async def aoutput(self, command: Command) -> ProcessResult: ...
    async def arun(self, command: Command) -> str: ...
    async def aexit_code(self, command: Command) -> int: ...
    async def aprobe(self, command: Command) -> bool: ...
    async def astart(self, command: Command) -> RunningProcess: ...
    def __repr__(self) -> str: ...

class ProcessError(Exception):
    """Base class for every error raised by this package."""

class NonZeroExit(ProcessError):
    """`run()` / `exit_code()` got a non-zero exit."""

    program: str
    code: int
    stdout: str
    stderr: str

class Timeout(ProcessError):
    """A run exceeded its configured timeout."""

    program: str
    timeout_seconds: float
    stdout: str
    stderr: str

class Cancelled(ProcessError):
    """A run was cancelled via a cancellation token (Phase 2 surface)."""

    program: str

class Signalled(ProcessError):
    """A run was killed by a signal."""

    program: str
    signal: int | None
    stdout: str
    stderr: str

class ProcessNotFound(ProcessError):
    """The program could not be found / spawned."""

    program: str

class ResourceLimit(ProcessError):
    """A resource limit (memory / processes / CPU) was invalid or exceeded."""

class Unsupported(ProcessError):
    """The operation is not supported on this platform."""
