"""Type stubs for the compiled `_processkit` extension module.

mypy cannot see into the PyO3 cdylib, so the public surface is declared here.
Keep this in sync with `src/lib.rs`.
"""

from __future__ import annotations

import os
from collections.abc import AsyncIterator, Sequence
from types import TracebackType
from typing import Literal

StrPath = str | os.PathLike[str]

class ProcessResult:
    """The captured result of a finished run. A non-zero exit, a timeout, and a
    signal-kill are all reported as data here — never raised by `output()`."""

    @property
    def stdout(self) -> str: ...
    @property
    def stderr(self) -> str: ...
    @property
    def code(self) -> int | None: ...
    @property
    def is_success(self) -> bool: ...
    @property
    def timed_out(self) -> bool: ...
    @property
    def signal(self) -> int | None: ...
    @property
    def program(self) -> str: ...
    @property
    def duration_seconds(self) -> float: ...
    def combined(self) -> str: ...
    def __repr__(self) -> str: ...

class Command:
    """A command builder. Builder methods return a new `Command`."""

    def __init__(self, program: StrPath, args: Sequence[str] | None = ...) -> None: ...
    def arg(self, arg: str) -> Command: ...
    def args(self, args: Sequence[str]) -> Command: ...
    def cwd(self, path: StrPath) -> Command: ...
    def env(self, key: str, value: str) -> Command: ...
    def stdin_bytes(self, data: bytes) -> Command: ...
    def stdin_text(self, text: str) -> Command: ...
    def keep_stdin_open(self) -> Command: ...
    def timeout(self, seconds: float) -> Command: ...
    def output(self) -> ProcessResult: ...
    def run(self) -> str: ...
    def exit_code(self) -> int: ...
    def probe(self) -> bool: ...
    async def aoutput(self) -> ProcessResult: ...
    async def arun(self) -> str: ...
    async def aexit_code(self) -> int: ...
    async def aprobe(self) -> bool: ...
    async def astart(self) -> RunningProcess: ...
    def __repr__(self) -> str: ...

class Outcome:
    """How a process ended."""

    @property
    def code(self) -> int | None: ...
    @property
    def signal(self) -> int | None: ...
    @property
    def timed_out(self) -> bool: ...
    @property
    def is_success(self) -> bool: ...
    def __repr__(self) -> str: ...

class Finished:
    """A process's outcome plus captured stderr (stdout was streamed)."""

    @property
    def outcome(self) -> Outcome: ...
    @property
    def stderr(self) -> str: ...
    @property
    def code(self) -> int | None: ...
    @property
    def is_success(self) -> bool: ...
    def __repr__(self) -> str: ...

class OutputEvent:
    """One captured line and the stream it came from."""

    @property
    def stream(self) -> str: ...
    @property
    def is_stderr(self) -> bool: ...
    @property
    def text(self) -> str: ...
    def __repr__(self) -> str: ...

class StdoutLines:
    """Async iterator over a process's stdout, line by line."""

    def __aiter__(self) -> AsyncIterator[str]: ...
    async def __anext__(self) -> str: ...

class OutputEvents:
    """Async iterator over stdout + stderr as interleaved `OutputEvent`s."""

    def __aiter__(self) -> AsyncIterator[OutputEvent]: ...
    async def __anext__(self) -> OutputEvent: ...

class ProcessStdin:
    """A writable handle to a running process's stdin (all methods awaitable)."""

    async def write(self, data: bytes) -> None: ...
    async def write_line(self, line: str) -> None: ...
    async def flush(self) -> None: ...
    async def close(self) -> None: ...

class RunningProcess:
    """A handle to a started process: stream output, write stdin, await exit."""

    @property
    def pid(self) -> int | None: ...
    def stdout_lines(self) -> StdoutLines: ...
    def output_events(self) -> OutputEvents: ...
    def take_stdin(self) -> ProcessStdin | None: ...
    def start_kill(self) -> None: ...
    async def wait(self) -> Outcome: ...
    async def finish(self) -> Finished: ...
    async def output(self) -> ProcessResult: ...
    async def shutdown(self, grace_seconds: float) -> Outcome: ...
    def __repr__(self) -> str: ...

class ProcessGroup:
    """A kill-on-drop container for a process tree; use as a (async) context manager."""

    def __init__(self) -> None: ...
    def __enter__(self) -> ProcessGroup: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: TracebackType | None = ...,
    ) -> Literal[False]: ...
    async def __aenter__(self) -> ProcessGroup: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: TracebackType | None = ...,
    ) -> Literal[False]: ...
    def start(self, command: Command) -> RunningProcess: ...
    async def astart(self, command: Command) -> RunningProcess: ...
    @property
    def mechanism(self) -> str: ...
    def members(self) -> list[int]: ...
    def shutdown(self) -> None: ...
    async def ashutdown(self) -> None: ...
    def __repr__(self) -> str: ...

class ProcessError(Exception):
    """Base class for every error raised by this package."""

class NonZeroExit(ProcessError):
    """`run()` / `exit_code()` got a non-zero exit."""

    program: str
    code: int
    stdout: str
    stderr: str

class Timeout(ProcessError):
    """A run exceeded its configured timeout."""

    program: str
    timeout_seconds: float
    stdout: str
    stderr: str

class Cancelled(ProcessError):
    """A run was cancelled via a cancellation token (Phase 2 surface)."""

    program: str

class Signalled(ProcessError):
    """A run was killed by a signal."""

    program: str
    signal: int | None
    stdout: str
    stderr: str

class ProcessNotFound(ProcessError):
    """The program could not be found / spawned."""

    program: str

class Unsupported(ProcessError):
    """The operation is not supported on this platform."""
