"""Generate the mdBook release-notes page from the root changelog.

Usage::

    python scripts/gen_changelog_page.py
    python scripts/gen_changelog_page.py --check
"""

from __future__ import annotations

import argparse
import pathlib

_ROOT = pathlib.Path(__file__).resolve().parents[1]
_SOURCE = _ROOT / "CHANGELOG.md"
_PAGE = _ROOT / "docs" / "changelog.md"
_EXAMPLES_URL = "https://github.com/ZelAnton/processkit-py/tree/main/examples/"
_PREFIX = """\
<!-- Generated by scripts/gen_changelog_page.py from ../CHANGELOG.md. Do not edit. -->
# Release notes

[\u2039 docs index](./)

"""


def build_page(source: pathlib.Path = _SOURCE) -> str:
    """Render the changelog as a book-local page with navigation chrome."""
    text = source.read_text(encoding="utf-8")
    first, separator, remainder = text.partition("\n")
    if first.strip() != "# Changelog" or not separator:
        raise ValueError(f"{source} must start with '# Changelog'")
    body = remainder.lstrip("\n")
    # Links in the root changelog are root-relative. Once the content lives
    # inside docs/, strip its `docs/` prefix and send non-book examples to the
    # repository so every rendered target remains valid.
    body = body.replace("](docs/README.md)", "](./)")
    body = body.replace("](docs/", "](")
    body = body.replace("](examples/)", f"]({_EXAMPLES_URL})")
    return _PREFIX + body


def check(source: pathlib.Path = _SOURCE, page: pathlib.Path = _PAGE) -> bool:
    """Whether the committed page exactly matches a fresh render."""
    return page.is_file() and page.read_bytes() == build_page(source).encode("utf-8")


def write(source: pathlib.Path = _SOURCE, page: pathlib.Path = _PAGE) -> None:
    """Write the generated page with LF line endings."""
    page.write_bytes(build_page(source).encode("utf-8"))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if docs/changelog.md is stale")
    args = parser.parse_args()
    if args.check:
        if not check():
            parser.exit(
                1,
                "docs/changelog.md is stale; regenerate it with: "
                "python scripts/gen_changelog_page.py\n",
            )
        print("docs/changelog.md is up to date.")
        return
    write()
    print(f"Wrote {_PAGE.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
